### PR TITLE
Add save-as button for python editor

### PR DESCRIPTION
**Pull request by RenWal**
This adds a "Save As" button for the Python Editor. (The icon will need some improvement though)

### CODE REVIEW

**Comment by RenWal** [comment]
This may collide with aaf793c from #49 as this replaces the save method entirely. If #50 is accepted, that commit is not required.

**Comment by swallat** [comment]
@RenWal could you please collect all changes and put it in one pull request. And please squash all commits into one single commit. Thanks, Sebastian

**Comment by RenWal** [comment]
Sorry for the commit mess. Will close #50 and #49 and submit a clean PR with both features later.

**Comment by RenWal** [comment]
Superseded by #53

**Pull request closed without merging**
