### PR TITLE
gui/graph_widget: Allow pan with middle mouse button

### PR DESCRIPTION
**Pull request by MonsterDruide1**
Using MMB to pan larger views is kind of standard, as far as I can tell, so I think it should also be possible in HAL. In this PR, I mostly just refactor the existing pan, to re-use the code when using MMB to pan the view.

### CODE REVIEW

**Review by joern274 — CHANGES_REQUESTED** [review]
Pan with middle mouse feature must not break existing rubberband selection feature

**Comment by MonsterDruide1** [comment]
Rubberband selection still works for me using LMB.

**Comment by joern274** [comment]
OK, maybe it is only me using the middle button exclusively for rubber-band selection since it does not trigger anything else. I'll poll the user whether they have strong preferences.

**Comment by joern274** [comment]
For example if the mouse pointer is on top of a node left mouse button will move that node rather than starting a rubber-band selection.

**Comment by MonsterDruide1** [comment]
> * Use Shift modifier together with middle button for pan

No, that's exactly what I want to avoid here. LMB + Pan-modifier already exists, but I want to pan the view without pressing additional buttons.

> * Introduce a new modifier for rubber-band selection and communicate the modified GUI behavior to the user.

That would work, although I'm not sure if rubber-banding with MMB is even required in the first place. I'm not an experienced user with the program, so I probably can't properly judge that, but as far as I can tell, clicking between nodes with LMB to start rubber-band-selection should always be possible.

> * Add a setting so the user can decide whether the middle button gets used for rubber-band selection or pan

If hte existing behaviour should be maintained (somehow) at any cost, that would be my preferred solution compared to adding another modifier key.

**Pull request merged**
