### PR TITLE
Feature/selection history

### PR DESCRIPTION
**Pull request by dertob**
Use the shortcuts 'a' and 'd' to traverse through your selection history.

### CODE REVIEW

**Comment by swallat** [comment]
Otherwise we should name it `gate_selection_history_navigator`?

**Comment by dertob** [comment]
> Should we name it `gate_selection_history_navigator` otherwise?

You've got a point there. Currently only gates are saved in the history. I think we talked about only saving gates one time? Adding nets to the history should be a quick job. Or do you prefer only navigating between the gate history and renaming the class?

**Comment by swallat** [comment]
I would actually prefer to include nets. Is this a huge effort to add?

**Comment by dertob** [comment]
Shouldn't be. I'm sure I will find a solution. If you want I will get on it.

While we are at it: What do you think how many elements should be saved in the history by default? Last time we talked we mentioned a rather small numer around 20 or so.

**Comment by swallat** [comment]
@dertob I think a buffer of 20-50 entries should be Ok for the first implementation. Could we maybe set it via configuration variable? Otherwise please add the support for nets in the history. Thanks.

**Comment by swallat** [comment]
@dertob I'm closing this PR for now. We can reopen it, when you are ready.

**Pull request closed without merging**
