### PR TITLE
Add installation dependencies for Linux Mint

### PR DESCRIPTION
**Pull request by citypw**
Linux Mint is based on Ubuntu. So this script works on Linux Mint as well.

### CODE REVIEW

**Comment by RenWal** [comment]
Confirmed successful build and run on fresh Mint 19.3.

One minor issue: Currently, the stylesheets are not entirely compatible:
Bildschirmfoto von 2020-05-06 17-25-38

At several places, white colors appear in our dark theme. We should fix this at some point.

@devhoffmann Do you agree that we should extend our compatibility list to Linux Mint and then deal with the style issue?

**Comment by devhoffmann** [comment]
I'd like to get @swallat 's opinion on this as well.
From my point of view we cannot claim support if we don't test on this platform ourselves.

**Comment by swallat** [comment]
I don't think that changing this file means we support Mint in general. As long as it is convenient to others we should add the change to install_dependencies.sh.

**Comment by swallat** [comment]
@devhoffmann Any update on this issue?

**Comment by RenWal** [comment]
Since the changes have been approved, can we merge this now?

**Pull request merged**
