### PR TITLE
Fix core event behaviour when creating empty netlist

### PR DESCRIPTION
**Pull request by RenWal**
Added method to create netlist with suppressed events. Previously, creating a new netlist would fire events but loading a netlist from file would not. This inconsistent behaviour was causing crashes since event handlers don't expect events for top module creation.

Refactored enabling and disabling of all event handlers into new method.
Documented event behaviour of netlist factory.

### CODE REVIEW

**Comment by RenWal** [comment]
Pipeline is failing because of unrelated tests

**Comment by devhoffmann** [comment]
@RenWal the factory function should still be called `create_netist`, I don't see a reason for renaming.

@all:
@Slowpoke42 suggested the opposite if I recall correctly: firing all events during netlist load.
I think this is the path we should follow, not suppressing everything.
Any comments?

**Comment by RenWal** [comment]
The reason for renaming is that the old function still exists. It can't be deleted because we need one that suppresses the events and one that doesn't.

**Comment by Slowpoke42** [comment]
The main problem with the current approach (not sending events during netlist creation) is that it requires EVERY subscriber to implement two separate synchronization paths, one for the initial setup and one to handle subsequent changes. Now of course this can be done, its just annoying for multiple reasons:

- Requires ~twice as much time to program
- Requires ~twice as much time to refactor
- Is ~twice as hard to understand
- Contains ~twice as many bugs

Sending events during netlist creation could simplify this. Subscribers would only need to implement handle methods for the relay events and would then be constructed automatically alongside the netlist (note that this requires the netlist to send events in a sensible order).

In most cases this would likely result in a small performance drop, but given that netlist creation is a one-off operation and constitutes only a tiny fraction of normal runtime this might be negligible.

HOWEVER this approach only works for subscribers that exist prior to netlist creation. Subscribers that are created after that would obviously still need to implement init() methods. So the usefulness of this approach kind of hinges on the question of how many of those we eventually end up with. (I think that number is currently zero, still important to keep in mind)

I'm not really chosing a side on this issue. I think you can argue for both positions and in the end it just comes down to wether you prefer slow but simple or fast but complex code here.

**Comment by RenWal** [comment]
@Slowpoke42 I see your point. Do you think we will experience problems when we eventually move to a multi-window system (or is this no longer planned?), since we _will_ then need to initialize widgets after netlist creation?

Also, given the overhead of Qt signals, how much of a performance drop do you anticipate on startup? From an optimization standpoint I agree that netlist loading is a one-shot operation and optimizing such code is usually wasted time. However, from a usability standpoint, if we load large netlists this might be an issue. Consider some netlist previously needing 10 seconds to load will now need 20 seconds. That would annoy me as a user.

**Comment by Slowpoke42** [comment]
It's important to keep in mind that user visible widgets aren't necessarily the netlist relays subscribers. Take for example the module widget:
The actual data is managed in a single global model that exists independently of the widgets for the entire runtime of the application. The module widget(s) itself are just views and do not contain any netlist data. So you could construct a hundred module widgets dynamically at runtime and you still wouldnt need any init methods.
I can't say if all future widgets will be able to centralize their data in such a way, but even if they won't it wouldn't really be a problem in the traditional sense of the word, it would just diminish the usefulness of sending signals during netlist creation (because we would have to implement init methods anyway, which are likely faster).

The performance overhead of sending events during netlist creation should be mainly dependent on the implementation of the handler methods. Currently we do very little with the events so I estiamte the overhead to be relatively small (if there is a noticeable performance difference at all). Performance could become a problem if we introduce a lot of data structures that take a lot of time to construct incrementally.

Oversimplified example:
Imagine you would want a sorted vector of all gates. If you construct this after netlist creation you can just create a vector of size number_of_gates, throw in all the gates, and then sort in place. This is obviously much faster then constructing an empty vector and then incrementally inserting gates one at a time at the right position, especially because you potentially have to resize your vector a billion times.

**Comment by devhoffmann** [comment]
Okay, for now I suggest the following:
the `make_empty_netlist` function is removed again, but the `event_controls` are kept.
If you need to suppress the events at some point, you can use the `event_controls` to do so.
As a consequence *none* of our internal functions should suppress events anymore.

From my point of view this should only require an additional change in the netlist parsing of the GUI where we now have to suppress events while parsing.
In future development we are then able to simply remove suppression if we want the GUI to react to the events while parsing

**Comment by RenWal** [comment]
I have rolled back the changes as per your request and moved event suppression from core to gui. The core now never suppresses events. All GUI functions that would cause events to be triggered before the GUI is fully initialized will now explicitly block events.

(Updating the GUI later on to actually handle events during parsing will take some time since some of our event handlers expect us to have a reference to the netlist object, which we don't have at that stage. Not complicated but lots of minor tweaks to do)

**Pull request merged**
